spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitlab-demo.com/2532105/config-repo.git
          username: 2532105
          password: 52601733
#          basedir: E:/config #本地仓库保存路径
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8700
logging:
  level:
    root: debug